### ISSUE TITLE
Seems like a mismatch between implementation code & mathematical formulation in the paper

### ISSUE THREAD

**Issue by Buhua-Liu** [xxgege/StableNet#1]
My understanding:
- RFF:  `random_fourier_features_gpu()` adds a new dimension of size `num_f` rather than performs dimension transformation.
- `lossb_expect(cfeaturec, num_f)` computes the square of the Frobenius norm of the original feature vector (of size `batch_size * feature_dimemsion` ) at each `num_f` dimension, then accumulating them minus the trace of covariance matrix gives the final loss. 

Question:
- Does `cfeaturec` refer to `A_i` and `B_i`, and `n` the batch size  in Eq. (3)?
- `num_f` refer to `n_A` and  `n_B` in Eq. (4)?
![image](https://user-images.githubusercontent.com/55881942/133263720-23cfde3a-ffef-46a1-aeca-d2b300ecca52.png)

**Comment by xxgege** [comment]
1. Actually, A and B refer to two variables and ![equation](http://www.sciweavers.org/upload/Tex2Img_1632282660/render.png) and ![equation](http://www.sciweavers.org/upload/Tex2Img_1632282760/render.png) refer to features of the representation, as described in Section 3.1 of the paper.   Thus cfeaturec does not refer to A_i and B_i, but (A_1, ..., A_n) and (B_1, ... ,B_n) refer to two variables in cfeature.  n refers to the batch size.
2. Actually, n_A and n_B are twice of num_f, because when we randomly sample one set of w and b for RFF, both sine and cosine of the feature are calculated.
